### ISSUE TITLE
No need for         if card_wins > 0

### ISSUE THREAD

**Issue by PiaFraus** [jfriar/adventofcode#1]
https://github.com/jfriar/adventofcode/blob/27ec89558cc28fcf74af73a9e26ff80dc4c0b836/2023/day4_2.py#L25C26-L25C26

No need for this check :) 
`for` would just not do anything if value is 0

**Comment by jfriar** [comment]
Oh man, you are right.  I had that in there before I changed how the loop was using range :facepalm:
